### ISSUE TITLE
парни у нас шрифт не отображается

### ISSUE THREAD

**Issue by sakuraskip** [sakuraskip/opiProject12#2]
друзья нам срочно нужен шрифт arial.ttf без него мы как без воздуха!!!!

**Comment by sakuraskip** [comment]
файлом метните сюда и все будет чиорио

**Comment by desynchrome** [comment]
[https://fonts-online.ru/fonts/arial/download](держи, для друзей не жалко)

**Comment by sakuraskip** [comment]
> [https://fonts-online.ru/fonts/arial/download](url) для друзей не жалко!!!!

красава!!!!!!!
