### ISSUE TITLE
доска почета

### ISSUE THREAD

**Issue by sakuraskip** [sakuraskip/opiProject12#3]
парни нам срочно нада доска почета нашей группы с фото/аватарками с позолоченной рамкой и крутой подписью а то мне впадлу

**Comment by thempra79** [comment]
![Uploading Снимок экрана 2023-12-28 225613.png…]()

**Comment by sakuraskip** [comment]
бро оно не открывется

**Comment by sakuraskip** [comment]
![authorspage](https://github.com/sakuraskip/opiProject12/assets/144053405/77db2e16-25f8-4af8-b375-9386afba71f6)
парни ну я красоту нарисовал

**Comment by sakuraskip** [comment]
парни ну я красоту нарисовал
![authorspage](https://github.com/sakuraskip/opiProject12/assets/144053405/0a3a7e70-3be5-4c6b-9ad4-c8c559f0d54d)
