### ISSUE TITLE
Создать модуль уменьшения количества платформ при достижении определенной высоты

### ISSUE THREAD

**Issue by thempra79** [sakuraskip/opiProject12#8]
Это задание будет выпонять Влад, как выполнишь модуль сделай его краткое описание, оно мне нужно для отчета

**Comment by sakuraskip** [comment]
сделано, ждем коммита!!!!!!!

**Comment by akainom** [comment]
коммит на мести краткое описание +- тоже

**Comment by sakuraskip** [comment]
красава
